apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  defaultBackend:
    service:
      name: default-http-backend
      port:
        number: 80
  rules:
  - host: microservices.info
    http:
      paths:
      - path: /employee
        pathType: Prefix
        backend:
          service:
            name: employee
            port:
              number: 8080
      # - path: /department
      #   backend:
      #     serviceName: department
      #     servicePort: 8080
      # - path: /organization
      #   backend:
      #     serviceName: organization
      #     servicePort: 8080
